### ISSUE TITLE
Add movies to trakt which are not watched (watchlist)

### ISSUE THREAD

**Issue by mweibel** [cytec/SynoDLNAtrakt#17]
Hi,

don't know if it's planned to do this but it would be nice if every movie (regardless of seen or not) would be added to the trakt.tv watchlist :)

Thanks a lot for it, since the last update it's possible to rate and mark as seen and it syncs with trakt.tv :)
- Michael

**Comment by cytec** [comment]
So you basicly want that every Movie which is added would ne added to the trakt watchlist?

**Comment by mweibel** [comment]
Exactly. That would be nice :D

Am 29.01.2013 um 00:19 schrieb cytec notifications@github.com:

**Comment by cytec** [comment]
ok ill see what i can do, maybe ill make it an option :)

**Comment by cytec** [comment]
should be working now, just enable it in the advanced config section, and leave the list name to watchlist...
you`ll be able to change the list name in the future so one can add movies to other lists than the default watchlist :)
