### ISSUE TITLE
raised an exception

### ISSUE THREAD

**Issue by macmotion** [cytec/SynoDLNAtrakt#18]
Hi Mate, 

First off thanks for putting the time into this app.. 

I'm running a ds1812+ with DSM 4.2-3202, python 2.7.3-5

and I'm getting a number of errors and nothing is loading into the interface.. 

I have tried to resolve them but with no luck and wanted to know if you could assist me. 

1) python 2.7.3-5 is it ok to run this version ?

2) 

24.03.2013 08:28:24 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2013-03-24 08:58:24.525721)" raised an exception
24.03.2013 08:28:24 DEBUG   : Fanart already exists
24.03.2013 08:28:24 DEBUG   : Cover already exists
24.03.2013 08:28:24 DEBUG   : FANARTPATH -> /usr/local/synodlnatrakt/var/cache/fanart/248682.jpg
24.03.2013 08:28:24 DEBUG   : COVERPATH -> /usr/local/synodlnatrakt/var/cache/cover/248682.jpg
24.03.2013 08:28:24 DEBUG   : Type: episode, Series: New.Girl.S02E19.Quick.Hardening.Caulk.mkv, Season: 2, Episode: 19
24.03.2013 08:28:24 INFO    : try to guess infos from Filename...
24.03.2013 08:28:24 ERROR   : Cant find/open/parse file: /volume1/video/Tv Series/New Girl/New.Girl.S02E19.Quick.Hardening.Caulk.nfo
24.03.2013 08:28:24 INFO    : Found result for New Girl -> Fullname: New Girl, tvdb_id: 248682, Year: 2011-09-20
24.03.2013 08:28:24 DEBUG   : Type: series, Name: New Girl, Season: 2, Episode: 19
24.03.2013 08:28:24 INFO    : Trying to guess infos from Filename...
24.03.2013 08:28:24 ERROR   : cant find/open file: /volume1/video/Tv Series/New Girl/tvshow.nfo
24.03.2013 08:28:24 INFO    : generate new Mediaelement for: 16150
24.03.2013 08:28:24 DEBUG   : synoindex result for 16150 -> /volume1/video/Tv Series/New Girl/New.Girl.S02E19.Quick.Hardening.Caulk.mkv
24.03.2013 08:28:24 INFO    : Job "parse_logs (trigger: interval[0:30:00], next run at: 2013-03-24 08:58:24.525721)" executed successfully
24.03.2013 08:28:24 INFO    : READLOG FINISHED
24.03.2013 08:28:24 INFO    : Parsing: /var/log/lighttpd/access.log gave 0 entry(s)
24.03.2013 08:28:24 INFO    : IMPORT FROM MEDIASERVER STARTED
24.03.2013 08:28:24 INFO    : Parsing MediaServer log file from: /var/log/lighttpd/access.log
24.03.2013 08:28:24 INFO    : Running job "mediaserver (trigger: interval[0:30:00], next run at: 2013-03-24 08:58:24.525721)" (scheduled at 2013-03-24 08:28:24.525721)
24.03.2013 08:28:24 DEBUG   : Next wakeup is due at 2013-03-24 08:58:24.525721 (in 1799.989333 seconds)
24.03.2013 08:28:24 INFO    : READLOG STARTED
24.03.2013 08:28:24 INFO    : Running job "parse_logs (trigger: interval[0:30:00], next run at: 2013-03-24 08:58:24.525721)" (scheduled at 2013-03-24 08:28:24.525721)
24.03.2013 08:28:24 DEBUG   : Looking for jobs to run
AAUnboundLocalError: local variable 'req' referenced before assignment
AA    return send("POST", req, args, returnStatus)
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/trakt.py", line 203, in add_to_list
AA    trakt.add_to_list(self, listname=config.list_name)
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/mediaelement.py", line 276, in generate
AA    m.generate()
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/main.py", line 106, in import_mediaserver
AA    main.import_mediaserver()
AA  File "/usr/local/synodlnatrakt/share/SynoDLNAtrakt/SynoDLNAtrakt.py", line 41, in mediaserver
AA    retval = job.func(_job.args, *_job.kwargs)
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/lib/apscheduler/scheduler.py", line 477, in _run_job
AATraceback (most recent call last):
24.03.2013 07:58:25 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2013-03-24 08:28:24.525721)" raised an exception
24.03.2013 07:58:25 DEBUG   : Fanart already exists
24.03.2013 07:58:25 DEBUG   : Cover already exists

Thanks for your help mate.. 

Let me know if you have a donation page at all or if I can help with testing..

**Comment by cytec** [comment]
seems like there is a problem while trakt trys to add the movie/episode to your list...
is add to list activated?
which list name are you useing?

i should definitively imporve the logging ...
python 2.7 is prefect ;)

which version do you have? latest git or spk?

EDIT:
ive just pushed some changes to this repo, there should be some logging for this now.
i ran a test drive here and cant get that error to show up...

maybe you have some non english characters in your listname?
also i dont reccomend useing that function at all... youll get some really big lists and heavy loading time when you visit them.

you should prefere to add those files to your collection...

**Comment by macmotion** [comment]
Thanks mate for writting back..

Add Movies to trakt.tv list  is ticketed..

I'm using my own "movielist" I did try default and nothing..

latest spk ... 20130318-4

Thanks for your help mate.. keen to get this woring..

**Comment by cytec** [comment]
ive pushed out a new spk today, please try updating it...

also try to disable add to list for testing and/or make sure you dont have any non english chars in the list name.

i dont reccomend useing the "add to list" funktion, you should better stick to the "add to collection" function cause you may get some really big lists and cause heavy loading times when you visit the list on trakt.tv

**Comment by macmotion** [comment]
Thanks buddy !! I have updated the package and it's loading my shows at the
moment.... !! =:)

I have also disabled add to list function as well....

Thanks heaps mate... looking forward to using it..

I will stat using it and let you know how I go...

**Comment by macmotion** [comment]
Thanks Josh !!

**Comment by cytec** [comment]
glad you got it working :)
