### ISSUE TITLE
Unable to install on DS212 - Python version not compatible !

### ISSUE THREAD

**Issue by NMNCRT** [cytec/SynoDLNAtrakt#22]
While trying to install SynoDLNAtrakt, an error message tells me I need the 2.7.3.3 version of Python - the only version I was able to install is the 2.7.3_011.

How did you manage to complete the installation ? 

Many thanks !

Regards

**Comment by cytec** [comment]
You can find the latest Python spk here:

http://www.synocommunity.com/faq#addSource
