### ISSUE TITLE
DLNA Target Filtering

### ISSUE THREAD

**Issue by mistergoodwin** [cytec/SynoDLNAtrakt#23]
A target device white-list to parse before continuing with a scrobble.

Since I don't want my personal trakt account filling up with stuff someone else has watched. Looking briefly through your code, I assumed it uses the debug log from the media server, but I couldn't find a way to read the file to see if this is achievable.

**Comment by cytec** [comment]
ill take a look at this

**Comment by cytec** [comment]
so... what kind of white list would you prefere?
filter by IP or by User-Agent?

**Comment by mistergoodwin** [comment]
User-Agent, It would be more friendly to users and will work regardless of a Dynamic IP configuration.
