### ISSUE TITLE
Nothing showing

### ISSUE THREAD

**Issue by galdwyn** [cytec/SynoDLNAtrakt#24]
I all,

I've done all the installing as requested (included Multimedia Server Diagnostic activation)

After many reboots, nothing happened.

I've configured series and movies path like this : /volume1/public/Videos/Series/,  /volume1/public/Videos/Films/

Trakt TV account is ok

In Logs, i've this information : Parsing : /var/log/lighttpd/acess.log gave 0 entry <- does it mean that it doesn t see series and films based on multimedia server log ?

Configuration : 
Synology DS112
DSM 4.2
MediaServer 1.1-2403

Ty.

BR

**Comment by cytec** [comment]
seems like there are no videos played over the DLNA server?
are there any entrys in  /var/log/lighttpd/acess.log?

**Comment by galdwyn** [comment]
Here the log, Ty.

10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:19:54 +0200] "GET /transcoder/jpegtnscaler.cgi/vscover/659.jpg HTTP/1.0" 200 5444 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:19:55 +0200] "GET /transcoder/jpegtnscaler.cgi/vscover/660.jpg HTTP/1.0" 200 2589 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:19:55 +0200] "GET /transcoder/jpegtnscaler.cgi/vscover/661.jpg HTTP/1.0" 200 5062 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:19:56 +0200] "GET /transcoder/jpegtnscaler.cgi/vscover/662.jpg HTTP/1.0" 200 7768 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:19:58 +0200] "GET /transcoder/jpegtnscaler.cgi/vscover/663.jpg HTTP/1.0" 200 4346 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:19:58 +0200] "GET /transcoder/jpegtnscaler.cgi/vscover/664.jpg HTTP/1.0" 200 4970 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:19:59 +0200] "GET /transcoder/jpegtnscaler.cgi/vscover/665.jpg HTTP/1.0" 200 5230 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:01 +0200] "HEAD /vs/NDLNA/662.mkv HTTP/1.0" 200 0 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:02 +0200] "GET /vs/NDLNA/662.mkv HTTP/1.0" 206 147245 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:02 +0200] "GET /vs/NDLNA/662.mkv HTTP/1.0" 206 38732 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:10 +0200] "GET /vs/NDLNA/662.mkv HTTP/1.0" 206 2 "-" "-"
10.0.0.5 - - [18/Aug/2013:21:20:10 +0200] "HEAD /vs/NDLNA/662.mkv HTTP/1.0" 200 0 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:43 +0200] "GET /vs/NDLNA/662.mkv HTTP/1.0" 206 23079218 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:49 +0200] "GET /vs/NDLNA/662.mkv HTTP/1.0" 206 12200391 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:52 +0200] "GET /vs/NDLNA/662.mkv HTTP/1.0" 206 10648721 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:52 +0200] "GET /vs/NDLNA/662.mkv HTTP/1.0" 206 200587 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:52 +0200] "GET /vs/NDLNA/662.mkv HTTP/1.0" 206 2 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:55 +0200] "HEAD /vs/NDLNA/663.mkv HTTP/1.0" 200 0 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:55 +0200] "GET /vs/NDLNA/663.mkv HTTP/1.0" 206 150141 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:20:55 +0200] "GET /vs/NDLNA/663.mkv HTTP/1.0" 206 39210 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:21:01 +0200] "GET /vs/NDLNA/663.mkv HTTP/1.0" 206 6496 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:21:02 +0200] "GET /vs/NDLNA/663.mkv HTTP/1.0" 206 2 "-" "-"
10.0.0.5 - - [18/Aug/2013:21:21:02 +0200] "HEAD /vs/NDLNA/663.mkv HTTP/1.0" 200 0 "-" "-"
10.0.0.5 - - [18/Aug/2013:21:21:12 +0200] "HEAD /vs/NDLNA/663.mkv HTTP/1.0" 200 0 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:21:15 +0200] "GET /vs/NDLNA/663.mkv HTTP/1.0" 206 19393295 "-" "-"
10.0.0.5 10.0.0.16:50002 - [18/Aug/2013:21:21:34 +0200] "GET /transcoder/jpegtnscaler.cgi/vscover/659.jpg HTTP/1.0" 200 4046 "-" "-"

**Comment by cytec** [comment]
maybe your useing a custom DLNA client?
couse my log looks something like this:

192.168.0.11 192.168.0.55:50002 - [17/Aug/2013:04:43:26 +0200] "GET /v/NDLNA/1771.avi HTTP/1.1" 206 3997602 "-" "Mozilla/5.0 (compatible; LG-HttpClient-v1.0.3 UPnP/1.1; MSIE 8.0; Windows NT 5.1; LG_UA; AD_LOGON=LGE.NET; .NET CLR 2.0.50727; .NET CLR 3.0.04506.30; .NET CLR 3.0.04506.648; LG_UA; AD_LOGON=LGE.NET; LG NetCast.TV-2011)"

also have you tired to update to the latest git version?

 Parsing : /var/log/lighttpd/acess.log gave 0 entry means that the parser was unable to find any matching lines in your log file... but it doesnt seem like an error of the parser couse that would throw out an "unable to parse line xyz" error...

**Comment by galdwyn** [comment]
Git version 1.8.3-3 is it good ?

I've found a denied permission here : 
19.08.2013 19:55:43 DEBUG   : Sending infos to trakt: URL: http://api.trakt.tv//user/library/movies/watched.json/860f1d1eda847c3b934a2d942eef110e13d21b12/groovy/min, Data: None, Method: GET
19.08.2013 19:55:42 INFO    : SYNCING MOVIES...
19.08.2013 19:55:42 INFO    : TRAKT SYNC STARTED
19.08.2013 19:55:42 INFO    : Running job "sync_trakt (trigger: interval[4:00:00], next run at: 2013-08-19 23:55:42.799735)" (scheduled at 2013-08-19 19:55:42.799735)
19.08.2013 19:55:42 DEBUG   : Next wakeup is due at 2013-08-19 20:24:42.799735 (in 1739.963372 seconds)
19.08.2013 19:55:42 DEBUG   : Looking for jobs to run
19.08.2013 19:54:44 INFO    : Job "update_checker (trigger: interval[4:00:00], next run at: 2013-08-19 23:54:42.799735)" executed successfully
19.08.2013 19:54:44 INFO    : You are running an unknown version of SynoDLNAtrakt. Run the updater to identify your version
19.08.2013 19:54:43 INFO    : Job "mediaserver (trigger: interval[0:30:00], next run at: 2013-08-19 20:24:42.799735)" executed successfully
19.08.2013 19:54:43 INFO    : IMPORT FROM MEDIASERVER FINISHED
AAIOError: [Errno 13] Permission denied: '/var/log/lighttpd/access.log'
AA    open(config.accesslog, 'w').close()
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/helper.py", line 174, in parseLog
AA    logelement = helper.parseLog()
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/main.py", line 104, in scanlogs
AA    main.scanlogs()
AA  File "/usr/local/synodlnatrakt/share/SynoDLNAtrakt/SynoDLNAtrakt.py", line 39, in parse_logs
AA    retval = job.func(_job.args, *_job.kwargs)
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/lib/apscheduler/scheduler.py", line 477, in _run_job
AATraceback (most recent call last):
19.08.2013 19:54:43 ERROR   : Job "parse_logs (trigger: interval[0:30:00], next run at: 2013-08-19 20:24:42.799735)" raised an exception
19.08.2013 19:54:43 INFO    : Parsing: /var/log/lighttpd/access.log gave 2 entry(s)
19.08.2013 19:54:42 INFO    : Parsing MediaServer log file from: /var/log/lighttpd/access.log
19.08.2013 19:54:42 INFO    : Retrieving latest version information from github
19.08.2013 19:54:42 INFO    : Running job "update_checker (trigger: interval[4:00:00], next run at: 2013-08-19 23:54:42.799735)" (scheduled at 2013-08-19 19:54:42.799735)
19.08.2013 19:54:42 INFO    : IMPORT FROM MEDIASERVER STARTED

**Comment by cytec** [comment]
oh well that sould be fixed easily:

shh to your DS as root and then type in terminal:
chmod 777 /var/log/lighttpd/access.log'

**Comment by galdwyn** [comment]
Ok now there is no more permissions errors, only snif : 

19.08.2013 20:29:35 ERROR   : No entry found for ID 662
19.08.2013 20:29:35 ERROR   : No entry found for ID 663
19.08.2013 20:29:35 INFO    : Job "mediaserver (trigger: interval[0:30:00], next run at: 2013-08-19 20:59:34.888808)" executed successfully
19.08.2013 20:29:35 INFO    : IMPORT FROM MEDIASERVER FINISHED
19.08.2013 20:29:35 INFO    : /var/log/lighttpd/access.log moved to backup directory: /usr/local/synodlnatrakt/var//accesslog-backups/130819-202935-access.log
19.08.2013 20:29:35 INFO    : Parsing: /var/log/lighttpd/access.log gave 2 entry(s)

**Comment by cytec** [comment]
please make sure your running the latest version by running git pull in terminal
seems like there is a problem with connecting to your MediaServer DB and/or you have entered the wrong directorys?
