### ISSUE TITLE
Cannot get real path...

### ISSUE THREAD

**Issue by MijoBarbaric** [cytec/SynoDLNAtrakt#27]
Hi!

Just tried to install this cool package on my DS713+. Installation seemed to be successful but it threw two errors:
- Cannot get real path of /var/packages/synodlnatrakt/target/indexdb/appindexdb
- Cannot get real path of /var/packages/synodlnatrakt/target/indexdb/helpindexdb

After starting and accessing it over port 1337 nothing appears and it suddenly stops. The log (/var/packages/synodlnatrakt/target/var/logs/SynoDLNAtrakt.log) is empty...

Thanks in advance and keep up the good work!

**Comment by cytec** [comment]
/var/packages/synodlnatrak/target should be a symlink to /volume1/@appstore/synodlnatrakt

i dont really know much about DSM so i cant probably tell you much about that, but i had that error once and a simple reinstall/restart of the package fixed it for me 

also make sure you have Mediaserver (in debug mode) and git installed and running

**Comment by demon326** [comment]
i'm verry sorry to bump this issue again, after houres of searching i found your great app and then all the issues with finding a git reppo(no IPK possible on my Syno..). Installed git, installed your app, and it gives the same error.

deleted, installed, deleted and so fort, but the problem persists.....

**Comment by cytec** [comment]
the app itself should work even with this error, if not im going to make a new spk after im back from my hollidays.

Git install should work anyway since there is no need to run any DSM specific stuff (symlinking etc)
just clone the repo and start it with python SynoDLNAtrakt.py start

**Comment by demon326** [comment]
hmm, i downloaded it in windows, now 'started' the app i think via /usr/local/python/bin/python  SynoDLNAtrakt.py start but when i go to ip:1337 there is nothing so i must be doing something els wrong .....

**Comment by cytec** [comment]
strange...
ill give that a closer look when im home again...

but manuall start should work anyway... testet it from here with a clean git clone and it works fine, maybe check the settings? any log file entrys?

**Comment by demon326** [comment]
I created two videos for you demonstrating what i do, so you can reproduce:

This one is via the user interface:
http://www.youtube.com/watch?v=7Ee_tPDo7VA

This one is via SSH, the git clone:
http://www.youtube.com/watch?v=DQHXxVFWCM4&feature=youtu.be

Since it works for you, it must be something i do wrong, but do notice i can't 'bootstrap' my syno, so can't do it that way..

**Comment by cytec** [comment]
ok so no ipkg...
well that makes things a little more complicated but it should be working anyway. ive watched both videos and couldn't find anything that was wrong...

but if you cant bootstrap you may install git and python spk from synocommunity and use them to clone/run SynoDLNAtrakt also make sure your DLNA Server runs in Debug mode (not sure if that forces SynoDLNAtrakt to exit) and double check your config file...

also i highly recommend to use a different folder for the git install (i have a complete network share for such stuff) so you can remember what was installed which way... 

Also you may must patch your local PATH before running it from source (without ipkg installed...) 

what DS Model do you use? 

if nothing helps try saveing this in the install folder and run it, then there should be a lot of output in the console ;)
https://gist.github.com/cytec/8138719

**Comment by demon326** [comment]
I have the 'Synology DS213j' version^^.  Bot both git and python from the synocommunity, the server is in debug mode like the readme says... 

also, can you enlighten me with the following parts: 'Also you may must patch your local PATH before running it from source"  and 'check your config file', because i don't know which file in which location you mention..

i'm used doing trial and error and i won't give up ^^

**Comment by cytec** [comment]
Oh sorry, i planed on attaching this as well, but seems like i've forget to.
1. The PATH variable is where your environment looks for executables so if you use synocommunity python and git you should do something like this: 
   PATH=/usr/local/python/bin/:/usr/local/git/bin/:$PATH 
   so theat the executables of git and python can be found...
2. checking the config: if you first start SynoDLNAtrakt (even if it doesn't run correctly) there should be a config.ini in the Same folder normaly that should all be ok but maybe somehow there is a different port given or something like that...
3. maybe you just use the debug script i uploaded in the last post, that should show you all stuff going on, seems like it kills itself on some point (maybe a file not found and i've missed to handle exceptions or something like that) but if you run said script you should be able to get a lot of feedback...

i won't give up if you won't :D

**Comment by demon326** [comment]
This is the info i have for you:
NAS> /usr/local/python/bin/python SynoDLNAtrakt_debug.py
Traceback (most recent call last):
  File "SynoDLNAtrakt_debug.py", line 14, in <module>
    from synodlnatrakt import web
  File "/volume1/SynoDLNAtrakt/synodlnatrakt/web.py", line 1, in <module>
    from synodlnatrakt.mediaelement import Episode, Movie
  File "/volume1/SynoDLNAtrakt/synodlnatrakt/mediaelement.py", line 4, in <module>
    from synodlnatrakt import pgsql, config, db, helper, images, trakt
  File "/volume1/SynoDLNAtrakt/synodlnatrakt/helper.py", line 23, in <module>
    tmdb3.set_locale(config.language, config.language)
  File "/volume1/SynoDLNAtrakt/lib/tmdb3/locales.py", line 143, in set_locale
    syslocale = Locale(language, country, sysenc)
  File "/volume1/SynoDLNAtrakt/lib/tmdb3/locales.py", line 92, in **init**
    self.country = Country.getstored(country)
  File "/volume1/SynoDLNAtrakt/lib/tmdb3/locales.py", line 51, in getstored
    .format(key, cls.**name**))
tmdb3.tmdb_exceptions.TMDBLocaleError: 'en' is not a known valid Country code.

Also, in what file do i have to add the 
" PATH=/usr/local/python/bin/:/usr/local/git/bin/:$PATH " and on what line? Trying to do my best so i can use this awesome app^^

edit: have it like this right now:

'PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:
export PATH
PATH=/usr/local/python/bin/:/usr/local/git/bin/:$PATH'

now i can use 'python <script.py> start, but same issue stays, hmm

edit: I manged to get IPKG installed(found a working way) but still the same issues....

**Comment by cytec** [comment]
ok i see, seems like the problem is that en_EN isn't a valid locale should be relatively easy to fix ill push a fix for that in a few... hopefully that will work ;)

**Comment by demon326** [comment]
Lets hope that fixes it!

**Comment by cytec** [comment]
here you go, should be a quick and dirty fix which allows you to use english language. ill have to take a deeper look at this stuff when im back home, for now it should work ;)

**Comment by demon326** [comment]
Yes! I can finally access the interface and it works! Thank you for your time^^.  When i have time and i have lots of time i'll suggest some interface changes, without writing any new css code, just using existing bootstrap classes^^

**Comment by cytec** [comment]
yeah nice to hear that.
sure go ahead ;)
