### ISSUE TITLE
Failed to run package service 

### ISSUE THREAD

**Issue by Fabhawk** [cytec/SynoDLNAtrakt#30]
Hi,
I installed all elements on my synology DS1512+ (DSM 4.3-3827) :
- GIT 1.8.4-3
- Python 2.7.6-7
- SynoDLNAtrakt 20140102-2

![capture](https://f.cloud.github.com/assets/6722834/2203055/165b8c5c-9913-11e3-88db-b67c1f5c1b1d.PNG)
I still get the following error :
![capture](https://f.cloud.github.com/assets/6722834/2203049/d402d108-9912-11e3-8291-3d048c601825.PNG)

Thanks in advance for your help !
F

**Comment by cytec** [comment]
Seems like there is a problem with the current spk... 
i have a look at it asap

EDIT: i've pushed a new version to my spk repo, please try deinstalling the current one and make a fresh install with the new one

**Comment by cytec** [comment]
@Fabhawk is everything working now?

**Comment by Fabhawk** [comment]
@cytec I just updated ! Working fine ! Thanks a lot, looking forward to try using it now !

**Comment by cytec** [comment]
glad i was able to help, have fun :)
