### ISSUE TITLE
No media at all!

### ISSUE THREAD

**Issue by Hayholten** [cytec/SynoDLNAtrakt#32]
Hello there!

Well, I'd like to use SynoDLNAtrakt on my DS413. Unfortunately, no media appears after the scan:

![capture](https://cloud.githubusercontent.com/assets/3150194/2749500/335e2c14-c808-11e3-8a70-8deb702a87dc.JPG)

Did I miss something?

Thanks for your answer ;-)

**Comment by Hayholten** [comment]
Hello again!

Here's the "ERROR" log:

21.04.2014 12:52:26 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 13:22:26.648094)" raised an exception
21.04.2014 12:52:26 ERROR   : No entry found for ID 3498
21.04.2014 12:22:26 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 12:52:26.648094)" raised an exception
21.04.2014 12:22:26 ERROR   : No entry found for ID 3498
21.04.2014 11:52:26 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 12:22:26.648094)" raised an exception
21.04.2014 11:52:26 ERROR   : No entry found for ID 3498
21.04.2014 11:40:25 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 12:09:55.337895)" raised an exception
21.04.2014 11:39:55 ERROR   : No entry found for ID 3498
21.04.2014 11:09:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 11:39:55.337895)" raised an exception
21.04.2014 11:09:55 ERROR   : No entry found for ID 3498
21.04.2014 10:39:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 11:09:55.337895)" raised an exception
21.04.2014 10:39:55 ERROR   : No entry found for ID 3498
AA
21.04.2014 10:09:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 10:39:55.337895)" raised an exception
21.04.2014 10:09:55 ERROR   : No entry found for ID 3498
21.04.2014 09:39:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 10:09:55.337895)" raised an exception
21.04.2014 09:39:55 ERROR   : No entry found for ID 3498
21.04.2014 09:09:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 09:39:55.337895)" raised an exception
21.04.2014 09:09:55 ERROR   : No entry found for ID 3498
21.04.2014 08:39:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 09:09:55.337895)" raised an exception
21.04.2014 08:39:55 ERROR   : No entry found for ID 3498
21.04.2014 08:09:55 ERROR   : No entry found for ID 3498
AAUnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 16: ordinal not in range(128)
AA    if curdir in dbresult.path:
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/helper.py", line 82, in get_media_type
AA    mediatype = helper.get_media_type(result.id)
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/main.py", line 208, in import_mediaserver
AA    main.import_mediaserver()
AA  File "/usr/local/synodlnatrakt/share/SynoDLNAtrakt/SynoDLNAtrakt.py", line 46, in mediaserver
AA    retval = job.func(_job.args, *_job.kwargs)
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/lib/apscheduler/scheduler.py", line 477, in _run_job
AATraceback (most recent call last):
21.04.2014 08:09:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 08:39:55.337895)" raised an exception
21.04.2014 07:40:25 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 08:09:55.337895)" raised an exception
AATimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30
AA    (self.size(), self.overflow(), self._timeout))
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/pool.py", line 780, in _do_get
AA    rec = self._connection_record = pool._do_get()
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/pool.py", line 431, in __init__
AA    return _ConnectionFairy(self).checkout()
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/pool.py", line 272, in connect
AA    self.pool.connect(),
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1661, in contextual_connect
AA    conn = bind.contextual_connect()
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 299, in _connection_for_bind
AA    return self.transaction._connection_for_bind(engine)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 803, in _connection_for_bind
AA    close_with_result=close_with_result)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 799, in connection
AA    **kw)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2357, in _connection_from_session
AA    close_with_result=True)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2366, in _execute_and_instances
AA    return self._execute_and_instances(context)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2353, in __iter__
AA    return list(res)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2149, in **getitem**
AA    ret = list(self[0:1])
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2282, in first
AA    dbresult = pgsql.session.query(pgsql.Video).filter(pgsql.Video.id == theid).first()
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/helper.py", line 75, in get_media_type
AA    mediatype = helper.get_media_type(key)
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/main.py", line 154, in scanlogs
AA    main.scanlogs()
AA  File "/usr/local/synodlnatrakt/share/SynoDLNAtrakt/SynoDLNAtrakt.py", line 42, in parse_logs
AA    retval = job.func(_job.args, *_job.kwargs)
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/lib/apscheduler/scheduler.py", line 477, in _run_job
AATraceback (most recent call last):
21.04.2014 07:40:25 ERROR   : Job "parse_logs (trigger: interval[0:30:00], next run at: 2014-04-21 08:09:55.337895)" raised an exception
21.04.2014 07:10:25 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 07:39:55.337895)" raised an exception
AATimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30
AA    (self.size(), self.overflow(), self._timeout))
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/pool.py", line 780, in _do_get
AA    rec = self._connection_record = pool._do_get()
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/pool.py", line 431, in __init__
AA    return _ConnectionFairy(self).checkout()
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/pool.py", line 272, in connect
AA    self.pool.connect(),
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1661, in contextual_connect
AA    conn = bind.contextual_connect()
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 299, in _connection_for_bind
AA    return self.transaction._connection_for_bind(engine)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 803, in _connection_for_bind
AA    close_with_result=close_with_result)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 799, in connection
AA    **kw)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2357, in _connection_from_session
AA    close_with_result=True)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2366, in _execute_and_instances
AA    return self._execute_and_instances(context)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2353, in __iter__
AA    return list(res)
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2149, in **getitem**
AA    ret = list(self[0:1])
AA  File "/usr/local/python/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2282, in first
AA    dbresult = pgsql.session.query(pgsql.Video).filter(pgsql.Video.id == theid).first()
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/helper.py", line 75, in get_media_type
AA    mediatype = helper.get_media_type(key)
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/synodlnatrakt/main.py", line 154, in scanlogs
AA    main.scanlogs()
AA  File "/usr/local/synodlnatrakt/share/SynoDLNAtrakt/SynoDLNAtrakt.py", line 42, in parse_logs
AA    retval = job.func(_job.args, *_job.kwargs)
AA  File "/volume1/@appstore/synodlnatrakt/share/SynoDLNAtrakt/lib/apscheduler/scheduler.py", line 477, in _run_job
AATraceback (most recent call last):
21.04.2014 07:10:25 ERROR   : Job "parse_logs (trigger: interval[0:30:00], next run at: 2014-04-21 07:39:55.337895)" raised an exception
21.04.2014 06:40:25 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 07:09:55.337895)" raised an exception
21.04.2014 06:39:55 ERROR   : No entry found for ID 3498
21.04.2014 06:10:25 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 06:39:55.337895)" raised an exception
21.04.2014 06:09:55 ERROR   : No entry found for ID 3498
21.04.2014 05:39:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 06:09:55.337895)" raised an exception
21.04.2014 05:39:55 ERROR   : No entry found for ID 3498
21.04.2014 05:09:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 05:39:55.337895)" raised an exception
21.04.2014 05:09:55 ERROR   : No entry found for ID 3498
21.04.2014 04:39:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 05:09:55.337895)" raised an exception
21.04.2014 04:39:55 ERROR   : No entry found for ID 3498
21.04.2014 04:09:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 04:39:55.337895)" raised an exception
21.04.2014 04:09:55 ERROR   : No entry found for ID 3498
21.04.2014 03:39:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 04:09:55.337895)" raised an exception
21.04.2014 03:39:55 ERROR   : No entry found for ID 3498
21.04.2014 03:09:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 03:39:55.337895)" raised an exception
21.04.2014 03:09:55 ERROR   : No entry found for ID 3498
21.04.2014 02:39:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 03:09:55.337895)" raised an exception
21.04.2014 02:39:55 ERROR   : No entry found for ID 3498
21.04.2014 02:09:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 02:39:55.337895)" raised an exception
21.04.2014 01:39:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 02:09:55.337895)" raised an exception
21.04.2014 01:09:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 01:39:55.337895)" raised an exception
21.04.2014 00:39:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 01:09:55.337895)" raised an exception
21.04.2014 00:09:55 ERROR   : Job "mediaserver (trigger: interval[0:30:00], next run at: 2014-04-21 00:39:55.337895)" raised an exception

Does it helps?

**Comment by Hayholten** [comment]
No one?

I keep trying because I really want to link my Syno to Trakt and I think that is the only way to do it...

**Comment by cytec** [comment]
Sorry for the late response, i have a loot to do at work atm...

Looks like your DS tries to encode your (french?) Cinéma folder (mostly the é) to ASCII which isn't working... i though i've forced it to use utf-8 a while ago... but seems like i missed it...

you can (for now) just try this solution:
insert this in SynoDLNAtrakt.py in line 12

```
if not hasattr(sys, "setdefaultencoding"):
    reload(sys)

sys.setdefaultencoding('UTF-8')
```

that should force set the encoding to utf-8

**Comment by Hayholten** [comment]
Hello there!

Don't be sorry, it's kind of you to respond ;-) And yes, I'm a French user of Synology...

But I have to confess that I'm almost complety a stranger of command lines. That's why I use Config File Editor to do that. After I have found the file (it takes several minutes to me), I did that:

!/usr/bin/env python
 -_\- coding: utf-8 -_-

import os
import sys
base_path = os.path.dirname(os.path.abspath(**file**))

 Insert local directories into path
sys.path.append(os.path.join(base_path, 'lib'))

if not hasattr(sys, "setdefaultencoding"):
    reload(sys)

sys.setdefaultencoding('UTF-8')
from synodlnatrakt.timer import sched
from synodlnatrakt import config
from lib.daemon import Daemon
from datetime import datetime, timedelta

class MyDaemon(Daemon):

```
def run(self):
    config.initialize()
    config.save_config()

    from synodlnatrakt import web
    from synodlnatrakt import main, versioncheck
    from lib.bottle import TEMPLATE_PATH

    versioncheck.getVersion()
    versioncheck.checkGithub()

    parse_logs_int = int(config.interval)
    mediaserver_int = int(config.interval)
    trakt_sync_int = 240  # int(config.interval) * 8

    starttime = datetime.now()



    @sched.interval_schedule(minutes=parse_logs_int, start_date=starttime + timedelta(minutes=1))
    def parse_logs():
        main.scanlogs()

    @sched.interval_schedule(minutes=mediaserver_int, start_date=starttime + timedelta(minutes=1))
    def mediaserver():
        main.import_mediaserver()

    @sched.interval_schedule(minutes=trakt_sync_int, start_date=starttime + timedelta(minutes=2))
    def sync_trakt():
        main.update_movies()

    @sched.interval_schedule(minutes=trakt_sync_int, start_date=starttime + timedelta(minutes=1))
    def update_checker():
        main.checkupdate()

    @sched.interval_schedule(minutes=trakt_sync_int ,start_date=starttime + timedelta(seconds=10))
    def generate_stats():
        main.generate_stats()

    if config.delete_orphans:
        @sched.interval_schedule(minutes=480, start_date=starttime+timedelta(minutes=60))
        def delete_orphans():
            main.delete_orphans()

    sched.start()
    main.update_db()
    #sched.print_jobs()

    TEMPLATE_PATH.insert(0, config.templatedir)

    web.run(host='0.0.0.0', port=config.port, debug=True, server="paste")

    # while True:
    #     pass
```

if len(sys.argv) == 3 and '--config' in sys.argv[2]:
    config.cfg_path = sys.argv[2].replace("--config=", "")
    config.initialize()
    config.save_config()

if **name** == "**main**":
    daemon = MyDaemon(os.path.join(config.datadir, "synodlnatrakt.pid"))
    if len(sys.argv) >= 2:
        if 'start' == sys.argv[1]:
            daemon.start()

```
    elif 'stop' == sys.argv[1]:
        daemon.stop()
    elif 'restart' == sys.argv[1]:
        daemon.restart()
    else:
        print "Unknown command"
        sys.exit(2)
        sys.exit(0)
else:
    print "usage: %s start|stop|restart" % sys.argv[0]
    sys.exit(2)
```

First, am I right?

Anyway, it doesn't solve the issue... Still nothing...

**Comment by Hayholten** [comment]
Little up! ;-)

**Comment by cytec** [comment]
thats kinda strange...
i use it on my DS with no errors and i have german umlauts so that should be the same "problem" for python then the french special chars...

**Comment by cytec** [comment]
can you test with the latest commit?
https://github.com/cytec/SynoDLNAtrakt/commit/deca4fcb60f5c1152a7eba0eecebd744a98318f8

hopefully that should work now... if its still not working, you may have to rename your Movie/Series main folder... cause the config file which stores the Main Folders seems to have some problems with utf-8 stings -.-
