### ISSUE TITLE
Trakt API key should be configureable

### ISSUE THREAD

**Issue by mweibel** [cytec/SynoDLNAtrakt#4]
Currently one has to change config.py in order to change the trakt API key.

This should be done from the webinterface (similar to trakt_user/pw)

**Comment by cytec** [comment]
trakt api key is a development key which is bound to SynoDLNAtrakt you DONT have to change it, just change user/pw in the webinterface :)

**Comment by mweibel** [comment]
ah ok.. I've just seen other usages of trakt.tv where you'd have to provide an API key ;)
