### ISSUE TITLE
Enhancement request: create .watched files after scrobbling

### ISSUE THREAD

**Issue by joshspry** [cytec/SynoDLNAtrakt#9]
Hi
Would it be possible to, at the same time a series or movie is scrobbled to Trakt, have a .watched file created in the same folder as the media path (ie /path/movies/filename/[filename].watched)? These are used by YAMJ in creating watched flags for the popcorn hour. 
Something similar is done by pchtrakt (also on github: https://github.com/pchtrakt/pchtrakt) when it scrobbles (called watchedFileCreation). 
Thanks so much!

**Comment by cytec** [comment]
yep should be possible to implement :)

**Comment by cytec** [comment]
should work now, ill add an option to turn it of in settings/webinterface soon

**Comment by joshspry** [comment]
Thanks so much cytec - looking forward to testing it out! Bit of a n00b question - what's the best way to update with the new files from the NAS? I originally downloaded through your repo on package centre. I've downloaded the amended files to the relevant spot on the nas, but am having trouble compiling the .pyc versions of the .py files. Thanks for your help!

**Comment by cytec** [comment]
currently the best way is to update the installed spk with the git installation. if you have ipkg on your NAS it should be easy:

Stop SynoDLNAtrakt 

ssh into your NAS
cd /volume1/@appstore/synodlnatrakt/share
mv SynoDLNAtrakt SynoDLNAtrakt.backup
git clone https://github.com/cytec/SynoDLNAtrakt
chown -R synodlnatrakt:root SynoDLNAtrakt

then you should be able to run it again (over the webinterface).
the current version also has an git update checker implemented, works great but sadly you still have to manually start SynoDLNAtrakt again after an update...

if you dont have git installed, you can still do it that way:

ssh into your NAS
cd /volume1/@appstore/synodlnatrakt/share
mv SynoDLNAtrakt SynoDLNAtrakt.backup
/usr/syno/bin/wget http://github.com/cytec/SynoDLNAtrakt/archive/2.0.zip --no-check-certificate 
unzip SynoDLNAtrakt-2.0.zip
rm -rf SynoDLNAtrakt-2.0.zip
mv SynoDLNAtrakt-2.0 SynoDLNAtrakt
chown -R synodlnatrakt:root SynoDLNAtrakt

i have plans to make a new spk, but idk when i find the time to do this...

**Comment by joshspry** [comment]
Thanks so much for that Cytec! Have got the updates installed and will let you know how I get along!

**Comment by cytec** [comment]
should be working, i close this issue, please report if its not working correctly
